# Uncomment the next line to define a global platform for your project
  platform :ios, '9.0'

target 'FinalGame' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftLint'
  pod 'PhysicsEngine', :git => 'https://github.com/cs3217/2018-ps4-CT15.git', :branch => 'v0.0.1'

  # Pods for FinalGame

  target 'FinalGameTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
